# Duke Encounters
duke:
  encounters:
    latest-amount: 10
    password-strengh: 10

# Session
server:
  session:
    timeout: 1800

spring:
  h2:
    console:
      path: /admin/h2-console
  resources:
    chain:
      enabled: true
  mvc:
    favicon:
      enabled: false

# Actuator
management:
  context-path: /admin
  security:
    enabled: true

security:
  basic:
    enabled: true
  user:
    name: admin
    password: admin

info:
  application:
    env: Production

# Logging
logging:
  file: /var/logs/duke-encounters.log
  pattern:
    console: "%d %-5level %marker %logger : %msg%n"
    file: "%d %-5level %marker [%thread] %logger : %msg%n"
  level:
    root: WARN
    org.springframework: ERROR
    org.hibernate: ERROR
    org.thymeleaf: ERROR